{% set name = "virtualenv" %}
{% set version = "20.26.1" %}
{% set checksum = "604bfdceaeece392802e6ae48e69cec49168b9c5f4a44e483963f9242eb0e78b" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: {{ build }}
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - virtualenv = virtualenv.__main__:run_with_catch

requirements:
  host:
    - python
    - pip
    - hatch-vcs >=0.3
    - hatchling >=1.17.1
  run:
    - python
    - distlib <1,>=0.3.7
    - filelock <4,>=3.12.2
    - platformdirs <5,>=3.9.1
    - importlib-metadata >=6.6 # [py<38]

test:
  # optional-dependencies.test can be found here if we want to add upstream tests down the line:
  # https://github.com/pypa/virtualenv/blob/main/pyproject.toml
  #source_files:
  #  - tests
  imports:
    - virtualenv
    - virtualenv.activation
    - virtualenv.app_data
    - virtualenv.config
    - virtualenv.create
    - virtualenv.discovery
    - virtualenv.run
    - virtualenv.seed
    - virtualenv.util
  commands:
    - pip check
    - virtualenv --help
    #- pytest --verbose
  requires:
    - pip
    #- pytest

about:
  home: https://virtualenv.pypa.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Virtual Python Environment builder
  description: |
    A tool for creating isolated virtual python environments.
  doc_url: https://virtualenv.pypa.io/
  dev_url: https://github.com/pypa/virtualenv

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz
