{% set name = "virtualenv" %}
{% set version = "20.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8b927684efc6f1cc206c9db297a570ab9ad0e51c16fa9e45487d36d1905c058

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - virtualenv = virtualenv.__main__:run_with_catch

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - distlib >=0.3.6,<1
    - filelock >=3.4.1,<4
    - importlib_resources >=5.4  # [py<37]
    - importlib-metadata >=4.8.3  # [py<38]
    - platformdirs >=2.4,<3

test:
  imports:
    - virtualenv
    - virtualenv.activation
    - virtualenv.app_data
    - virtualenv.config
    - virtualenv.create
    - virtualenv.discovery
    - virtualenv.run
    - virtualenv.seed
    - virtualenv.util
  commands:
    - pip check
    - virtualenv --help
  requires:
    - pip

about:
  home: https://virtualenv.pypa.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Virtual Python Environment builder
  description: |
    A tool for creating isolated virtual python environments.
  doc_url: https://virtualenv.pypa.io/
  dev_url: https://github.com/pypa/virtualenv

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz
