{% set name = "virtualenv" %}
{% set version = "20.28.0" %}
{% set checksum = "2c9c3262bb8e7b87ea801d715fae4495e6032450c71d2309be9550e7364049aa" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: {{ build }}
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - virtualenv = virtualenv.__main__:run_with_catch

requirements:
  host:
    - python
    - pip
    - hatch-vcs >=0.3
    - hatchling >=1.17.1
  run:
    - python
    - distlib >=0.3.7,<1
    - filelock >=3.12.2,<4
    - platformdirs >=3.9.1,<5

test:
  requires:
    - pip
  # Missing pytest-env and pytest-mock so most tests do not work.
#    - flaky >=3.7
#    - packaging >=23.1
#    - pytest >=7.4
#    - pytest-env >=0.8.2
#    - pytest-mock >=3.11.1
#    - pytest-randomly >=3.12
#    - pytest-timeout >=2.1
#  source_files:
#    - tests
#    - pyproject.toml
  imports:
    - virtualenv
    - virtualenv.activation
    - virtualenv.activation.bash
    - virtualenv.activation.batch
    - virtualenv.activation.cshell
    - virtualenv.activation.fish
    - virtualenv.activation.nushell
    - virtualenv.activation.powershell
    - virtualenv.activation.python
    - virtualenv.app_data
    - virtualenv.config
    - virtualenv.config.cli
    - virtualenv.create
    - virtualenv.discovery
    - virtualenv.run
    - virtualenv.run.plugin
    - virtualenv.seed
    - virtualenv.seed.embed
    - virtualenv.seed.wheels
    - virtualenv.util
    - virtualenv.util.path
    - virtualenv.util.subprocess
  commands:
    - pip check
    - virtualenv --help

about:
  home: https://virtualenv.pypa.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Virtual Python Environment builder
  description: |
    A tool for creating isolated virtual python environments.
  doc_url: https://virtualenv.pypa.io/
  dev_url: https://github.com/pypa/virtualenv

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz
