{% set name = "virtualenv" %}
{% set version = "20.24.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8b927684efc6f1cc206c9db297a570ab9ad0e51c16fa9e45487d36d1905c058

build:
  # trigger 1
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - virtualenv = virtualenv.__main__:run_with_catch

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - hatch-vcs >=0.3
    - hatchling >=1.17.1
  run:
    - python
    - distlib >=3.9.1
    - filelock >=3.12.2
    - importlib_metadata >=6.6  # [py<38]
    - platformdirs >=3.9.1

test:
  source_files:
    - tests
  imports:
    - virtualenv
    - virtualenv.activation
    - virtualenv.app_data
    - virtualenv.config
    - virtualenv.create
    - virtualenv.discovery
    - virtualenv.run
    - virtualenv.seed
    - virtualenv.util
  commands:
    - pip check
    - virtualenv --help
    - pytest --verbose tests
  requires:
    - pip
    - flaky >=3.7
    - packaging >=23.1
    - pytest =7.4
    # - pytest-env >=0.8.2
    # - pytest-freezer >=0.4.8
    # - pytest-mock >=3.11.1
    - pytest-randomly >=3.12
    - pytest-timeout >=2.1

about:
  home: https://virtualenv.pypa.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Virtual Python Environment builder
  description: |
    A tool for creating isolated virtual python environments.
  doc_url: https://virtualenv.pypa.io/
  dev_url: https://github.com/pypa/virtualenv

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz
