{% set version = "20.16.2" %}

package:
  name: virtualenv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/virtualenv/virtualenv-{{ version }}.tar.gz
  sha256: 0ef5be6d07181946891f5abc8047fda8bc2f0b4b9bf222c64e6e8963baee76db

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - virtualenv = virtualenv.__main__:run_with_catch

requirements:
  build:
    - python                                 # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=41.0.0
    - setuptools_scm >=2
    - wheel >=0.30.0
  run:
    - python
    - appdirs >=1.4.3,<2
    - distlib >=0.3.1,<1
    - filelock >=3.2,<4
    - importlib-metadata >=0.12  # [py<38]
    - importlib_resources >=1.0  # [py<37]
    - platformdirs >=2,<3

test:
  imports:
    - virtualenv
    - virtualenv.activation
  commands:
    - pip check
    - virtualenv --help
  requires:
    - pip

about:
  home: https://virtualenv.pypa.io/
  license: MIT
  license_file: LICENSE
  summary: Virtual Python Environment builder
  description: |
    A tool for creating isolated virtual python environments.
  doc_url: https://virtualenv.pypa.io/
  dev_url: https://github.com/pypa/virtualenv

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz
