# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QIM+KnHNgDNO9N62u2Zi7O/40ZRg4btkBR1btVpgBfLGl57iZ9rcuhkmlXhXQAbkb4zHjmv5uidEFszIPJcWGHa18EL9IPwvuI/4DmWq8K5DDua8Q66eYg4Whatv4TCJII9Gh+IqhHV7IGiKtl38/7F9T7/MPPtGyqWHavR769j60OQsThWdI8ug5x7BCAoeS8EhrN45jMfs5hLA1kzODtzJVq3SobzGXG8msg9sxCQEwUcYFEaNarhpAOBxwuaLwAlo1z/MHJTShGXbV4XAsR4aTOIEKXrQvTQj//YtW88YUZPQLgepvpBl0x0uE3+sO39WimJ9DY9v4ZPEupdym3TinluiLkVzBVXmuUGFTOz8ONrwlwdn5HOUbJPmALlEIhxt7U8rB5mri7WY8YRxKqGz7FnmcDlS+ReMQzaBeWqluHHykyK8c8BqHRFZMJlEVTpDS8rNjhRRk4UsDuczw57xTvqe0PHobKq9feJXWmM6yU+fXSwQiB7tZ6JyaACbUIkqoTucuTttMDcQNKXnxwaOdBF6tCb5JseuhaMD1bpapxProOzYDTgn7AlrY+abjsYI0FqS2HHhpr6FRQKNsE88GxwlcFSV65ItFz7AxtVdmHm/H1IBBwTjBX9kyfUiHjdK4JggmxdF4yvLVueFjor3XVSXu/aaZbFAenG7dv8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
