travis:
  secure:
    BINSTAR_TOKEN: QIM+KnHNgDNO9N62u2Zi7O/40ZRg4btkBR1btVpgBfLGl57iZ9rcuhkmlXhXQAbkb4zHjmv5uidEFszIPJcWGHa18EL9IPwvuI/4DmWq8K5DDua8Q66eYg4Whatv4TCJII9Gh+IqhHV7IGiKtl38/7F9T7/MPPtGyqWHavR769j60OQsThWdI8ug5x7BCAoeS8EhrN45jMfs5hLA1kzODtzJVq3SobzGXG8msg9sxCQEwUcYFEaNarhpAOBxwuaLwAlo1z/MHJTShGXbV4XAsR4aTOIEKXrQvTQj//YtW88YUZPQLgepvpBl0x0uE3+sO39WimJ9DY9v4ZPEupdym3TinluiLkVzBVXmuUGFTOz8ONrwlwdn5HOUbJPmALlEIhxt7U8rB5mri7WY8YRxKqGz7FnmcDlS+ReMQzaBeWqluHHykyK8c8BqHRFZMJlEVTpDS8rNjhRRk4UsDuczw57xTvqe0PHobKq9feJXWmM6yU+fXSwQiB7tZ6JyaACbUIkqoTucuTttMDcQNKXnxwaOdBF6tCb5JseuhaMD1bpapxProOzYDTgn7AlrY+abjsYI0FqS2HHhpr6FRQKNsE88GxwlcFSV65ItFz7AxtVdmHm/H1IBBwTjBX9kyfUiHjdK4JggmxdF4yvLVueFjor3XVSXu/aaZbFAenG7dv8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
