travis:
  secure:
    BINSTAR_TOKEN: Zp3DkWnAbmq93m4mtQz5EJ+D4MSg3CnsIiYJcVOpNJVD4ZVG9Qrtr7yd8cN5nvTWffWcKO/nnJXSEHAxQVbgWPKIP6bMs4BqSk2Ht7HlFs4isXLCTM16tvCobwtN6jy0DDj/s72/K9ue/7viFhAg9fAUf5cO9SLI97XCV+xlLckVzDUNBy3O2jCReFk4cyq1EmK2pw4N2nW0FXWUqEHmPJGbttJHRD79fIVlJTKmEwSUDOibcEaxYbeCAQF+LCQ7nbEffrAzKQakcSwQFN9yxM2HhsBX96w2Cr67VkJIjYTRcBiZahoy87tRuasztJscTKvPuTFTpqhhyfp5rGQ6hYJafZCHRcnle94hbvLiKxD9VnZHzVFzzhg9H+T7j8DLZRo1JcwL5f5Au9xAOi2P64ojMcSF/FXEWAnV6fl7uGtrnclb4iHMLMu9Y26IdnGCenwpEjDUY7r0k/d6TYUlAEvekrsabQWt43RBK7XnGZ6XSgY04XeTo+qaAa9JyTE1Bewkmu5fu0Ym2SDR+Cu9Ij+KNXeVvCS4h9WJFBiIvt7W29MAriXdYUbG0t+8Y4KeR4uW9Wh3c9iuLzyiRbzoxmApb0qrH8x0/spxDSvelXTHNBxlzjqjh6HqW9rzxyZZxUJbyti472O5N8xx6k7jwceX5OoC/ZDagg+nt1wmiq8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
